### PR TITLE
Code best practices #7

### PR DESCRIPTION
**Pull request by ramakrishna-j**

### CODE REVIEW

**Comment by ramakrishna-j** [comment]
Pull request for assignment 3.1 with issue id - code_best_practices/Assignment_3.1 #7

**Comment by Manishky0708** [comment]
Hi @ramakrishna-j , Could you please assignment details and add the final screenshot?

**Comment by Manishky0708** [comment]
Hi @ramakrishna-j , I'm not able to see ingest_data.py, train.py and score.py in your code. Could you please add these files?

**Comment by ramakrishna-j** [comment]
image
Html document index

**Pull request merged**
